// Generated by CoffeeScript 1.3.3
(function() {
  var apiProxy, app, express, httpProxy, routingProxy;

  httpProxy = require('http-proxy');

  express = require('express');

  routingProxy = new httpProxy.RoutingProxy();

  apiProxy = function(pattern, host, port) {
    return function(req, res, next) {
      if (req.url.match(pattern)) {
        return routingProxy.proxyRequest(req, res, {
          host: host,
          port: port
        });
      } else {
        return next();
      }
    };
  };

  app = express();

  app.configure(function() {
    this.use(apiProxy('/ToolBox', '192.168.10.1', '85'));
    return this.use(express.bodyParser());
  });

  app.get('/Test', function(req, res) {
    return res.send('Hi');
  });

  app.listen(7000);

}).call(this);
