// Generated by CoffeeScript 1.3.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.configure(function() {
    app.set('views', "" + __dirname + "/public/views");
    app.set('view engine', 'jade');
    app.use(express["static"]("" + __dirname + "/public"));
    app.use(express.bodyParser());
    return app.use(app.router);
  });

  require('./routes').routes(app);

  app.listen(8000);

}).call(this);
