// Generated by CoffeeScript 1.3.3
(function() {
  var routes;

  routes = function(app) {
    require('./routes/default')(app);
    return require('./routes/users')(app);
  };

  module.exports = {
    routes: routes
  };

}).call(this);
